# Site settings
title: Yoochan Lee
description: Yoochan Lee' Profile
favicon: /assets/img/GYG_logo.png
baseurl: https://leeyoochan.github.io/
url: https://leeyoochan.github.io/
rss_url: /pages/atom.xml
google_analytics: UA-63653234-1

# Build settings
markdown: kramdown

exclude: [vendor]

# Author settings
author:
  name: Yoochan Lee
  title: Vulnerability Researcher
  address: Seoul, South Korea
  email: yoochan1026@gmail.com
  link: http://leeyoochan.github.io
  weibo:
  github: leeyoochan
  linkedin: 
  twitter: 
  gavatar: /assets/img/profile.jpeg
  stackoverflow:
#  stackoverflow: 4582127
  workHistory:
    - work1:
      company: XXX Ltd
      location: Auckland, New Zealand
      title: Java Developer
      started: 2014
      duration: (2014 - Present)
      description: I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description.
    - work2:
      company: XXX Ltd
      location: Shanghai, China
      title: Java Developer
      started: 2012
      duration: (2012 - 2014)
      description: I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description.
    - work3:
      company: XXX Ltd
      location: Shanghai, China
      title: Java Developer
      started: 2009
      duration: (2009 - 2012)
      description: I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description.
  educationHistory:
    - education1:
      organization: Hanyang University
      location: Seoul, South Korea
      degree: B.S
      major: Computer Science Engineering
      started: 2012
      duration: (2012 - 2018)
      description: I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.Is am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description.
  ctfHistory:
    - ctf1:
      name: DEFCON 25 CTF
      year: 2017
      rank: 9th
      teamname: RRR
      location: Las Vegas, NV, USA
    - ctf2:
      name: SECCON CTF
      year: 2016
      teamname: GYG
      rank: 12th
      location: Tokyo, Japan     
  languages:
    - language1:
      name: Korean
      proficiency: Native
    - language2:
      name: English
      proficiency: Limit
  programmingSkills:
    - skill1:
      name: C
      percentage: 50%
    - skill2:
      name: Python
      percentage: 70%
